### ISSUE TITLE
zhe ge pa cong xian zai hai neng yong ma

### ISSUE THREAD

**Issue by Bearshanjun** [satrong/node-webcrawler#2]
jin tian shi le xia zhe ge pa cong zhong de li zi , qi zhong  jing dong de li zi pao li hen chang shi jian ye mei fan ying , shi zhe ge jing dong de li zi bu neng yong le hai shi zhe ge pa cong yi jing bu neng yong le
 --2018/10/29

**Comment by satrong** [comment]
抱歉了啊，我好久没维护了，可能例子中的网站html结构有更新导致爬虫规则变了

**Comment by satrong** [comment]
修复了一下，目前是可以使用的
